### ISSUE TITLE
Support anonymous functions without React.FC

### ISSUE THREAD

**Issue by echenley** [milesj/babel-plugin-typescript-to-proptypes#10]
```js
import React from 'react';

type Props = {
  foo: string,
};

// this produces proptypes
function Example(props: Props) {
  return <div />
}

// and this produces proptypes
const Example: React.FC<Props> = (props) => {
  return <div />
};

// but this does not produce proptypes
const Example = (props: Props) => {
  return <div />
};
```

In my experience, the last example is the most common/intuitive way of writing a function component with types. Is there a technical reason why that case is handled differently than the other two?

The README documents this pretty well, but from a naive user's perspective it seems like an arbitrary distinction. I think it's worthwhile to support this pattern if possible.

**Comment by milesj** [comment]
Technically the last example is not a React component in the eyes of the type system (and technically neither is the first), they are simply functions. But you're right, I should probably support the last example also.

**Comment by milesj** [comment]
Implemented.

**Comment by echenley** [comment]
Amazing, thanks for the quick turnaround!
