### ISSUE TITLE
Usage with create-react-app --typescript?

### ISSUE THREAD

**Issue by jordyvandomselaar** [milesj/babel-plugin-typescript-to-proptypes#11]
At work we use `create-react-app --typescript` to set up new projects, is it possible to integrate this without ejecting?

**Comment by milesj** [comment]
@jordyvandomselaar I don't use `create-react-app`, so I don't really understand your question.

**Comment by jordyvandomselaar** [comment]
I want to use this plugin but I am using `create-react-app`, I'd like to know if it's possible to do this

**Comment by milesj** [comment]
@jordyvandomselaar As I said previously, I have no idea how `create-react-app` works. If you can configure Babel, then yes, you can use it, just add this plugin to the list.

**Comment by jordyvandomselaar** [comment]
Alright, that makes sense. Thanks for the replies! I'll close it for now.

For anyone else wondering; you cannot without using create-react-app rewired or something similar.

**Comment by kozlovvski** [comment]
Reopening this for the sake of an example.

@jordyvandomselaar did you have any luck setting this up with e.g. `react-app-rewired` and `customiza-cra`? I am looking for a way to use this package without ejecting, but having hard time to do so
