### ISSUE TITLE
Does not work with Pick<>

### ISSUE THREAD

**Issue by city41** [milesj/babel-plugin-typescript-to-proptypes#15]
This is a great plugin, thanks for making it!

I have found it doesn't work with `Pick<>`. I have forked the repo and added a fixture

```
import React from 'react';

interface SomeType {
  someString: string;
  someNumber: number;
}

type PropData = Pick<SomeType, 'someString'>;

type Props = PropData & {additionalString: string};

export const PickFromTypeFunctionComponent: React.FunctionComponent<
  Props
> = () => {
  return null;
};
```

and the resulting snapshot is

```
exports[`babel-plugin-typescript-to-proptypes transforms ./fixtures/pick-from-type.ts 1`] = `
"import _pt from 'prop-types';
import React from 'react';
interface SomeType {
  someString: string;
  someNumber: number;
}
type PropData = Pick<SomeType, 'someString'>;
type Props = PropData & {
  additionalString: string;
};
export const PickFromTypeFunctionComponent: React.FunctionComponent<Props> = () => {
  return null;
};
PickFromTypeFunctionComponent.propTypes = {
  additionalString: _pt.string.isRequired
};"
`;
```

I am currently investigating and seeing if I can add support for this. If I succeed, I can send a PR your way.

**Comment by city41** [comment]
On the surface this doesn't look very straightforward. It's possible to dig in and detect `Pick`, but it just snowballs from there, like what about `Pick<A, keyof Foo>`? need to detect keyof, etc.

**Comment by milesj** [comment]
@city41 Yeah this might be a bit complicated. May be one of those features that require the TS type checker to work correctly.

**Comment by milesj** [comment]
Not going to support this.
