### ISSUE TITLE
example shows @babel/preset-react, should be '@babel/plugin-syntax-jsx'

### ISSUE THREAD

**Issue by shcarrico** [milesj/babel-plugin-typescript-to-proptypes#20]
The example instructions specify using `@babel/preset-react`. To produce the transform you are showing in the readme, I think it should be suggesting use of `@babel/plugin-syntax-jsx` instead.. Using preset react transforms your JSX into JS. 

Perhaps I am wrong but, but i had much more luck with the below.

```js
module.exports= {
  presets: ['@babel/preset-typescript'],
  plugins: ['@babel/plugin-syntax-jsx',['babel-plugin-typescript-to-proptypes', { typeCheck: true }]]
}

```

**Comment by milesj** [comment]
I use the `react` preset myself without issue. However, I'll add a note of this to the readme.
