### ISSUE TITLE
Does not work with forwardRef

### ISSUE THREAD

**Issue by LankyLou** [milesj/babel-plugin-typescript-to-proptypes#22]
When using React.forwardRef, the proptypes are not generated.

**Comment by milesj** [comment]
@LankyLou Are you doing something like this?

```ts
const Comp = React.forwardRef();

Comp.propTypes = {};
```

**Comment by milesj** [comment]
@LankyLou Bump.

**Comment by vdh** [comment]
I'm doing something like this:
```jsx
const Comp = forwardRef((props, ref) => { /* … */ });
Comp.displayName = "Comp";
Comp.defaultProps = { /* … */ };
export default Comp;
```

**Comment by milesj** [comment]
I'm not sure how to support this properly since half the time there isn't any type information for the props, for example.

```
const RefComp = React.forwardRef((props, ref) => <OtherComp ref={ref} {...props} />);
```

The types are usually defined on `OtherComp`, which can be located anywhere. This seems like a feature that'll require the type checker.

**Comment by vdh** [comment]
@milesj Is there a way to hint the proper type for the `props` so that the plugin can manually generate prop types for situations like this? Something like:

```tsx
type CompProps = { foo: string };
const Comp = forwardRef<HTMLDivElement>((props: CompProps, ref) => { /* … */ });
/* babel-plugin-typescript-to-proptypes ["Comp", "CompProps"] */
Comp.displayName = "Comp";
Comp.defaultProps = { /* … */ };
export default Comp;
```
So the plugin can skip attempts at finding the `Comp` component and `CompProps` type, and just output something like `Comp.propTypes = { foo: PropTypes.string() };`?

**Comment by vdh** [comment]
P.S. Sorry I forgot to write that earlier example as Typescript

**Comment by milesj** [comment]
@vdh Yeah, that's about the only solution atm.

**Comment by milesj** [comment]
This should work now.

**Comment by LankyLou** [comment]
@milesj Thanks for this, it works great for me now

**Comment by sageknives** [comment]
> @milesj Is there a way to hint the proper type for the `props` so that the plugin can manually generate prop types for situations like this? Something like:
> 
> ```tsx
> type CompProps = { foo: string };
> const Comp = forwardRef<HTMLDivElement, CompProps>((props, ref) => { /* … */ });
> /* babel-plugin-typescript-to-proptypes ["Comp", "CompProps"] */
> Comp.displayName = "Comp";
> Comp.defaultProps = { /* … */ };
> export default Comp;
> ```
> 
> So the plugin can skip attempts at finding the `Comp` component and `CompProps` type, and just output something like `Comp.propTypes = { foo: PropTypes.string };`?

I can't seem to get this to work with forwardRef. 
Is there a specific line i need to add? I noticed in your tests you named the type RefProps, which didn't seem to work.
```/* babel-plugin-typescript-to-proptypes ["Comp", "CompProps"] */``` is this needed?
are defaultProps needed? 
Is there an example somewhere of how to write forwardRef with typescript to get the proptypes to work?

**Comment by milesj** [comment]
You type the generics like this: https://github.com/milesj/babel-plugin-typescript-to-proptypes/blob/master/tests/fixtures/memo-ref-components.tsx#L12

Your types must be in the same file.

**Comment by sageknives** [comment]
Thanks, that helped!
