### ISSUE TITLE
Using Mapped Types does not yield any prop type

### ISSUE THREAD

**Issue by emmenko** [milesj/babel-plugin-typescript-to-proptypes#23]
Given this usage of Mapped Types (meaning _an index signature where index strings can be members of a union of literal strings_):

```ts
export type Color = "red" | "green";
export type Props {
  colors: {
    [key in Color]: boolean;
  };
}
```

Then, there are no resulting prop types associated to the prop `color`.

You can see it from the following failing spec:

<img width="1183" alt="Screenshot 2019-09-11 at 11 36 05" src="https://user-images.githubusercontent.com/1110551/64686203-90b60700-d488-11e9-967e-6465acea7f20.png">

**Comment by emmenko** [comment]
@milesj I'd like to try to fix this, could you point me to the right direction where I should be looking at in the code?

**Comment by milesj** [comment]
@emmenko You would probably add another if conditional here: https://github.com/milesj/babel-plugin-typescript-to-proptypes/blob/master/src/convertBabelToPropTypes.ts#L24

**Comment by milesj** [comment]
Will be supported in the next version.
