### ISSUE TITLE
Generated propTypes are wrong when external types are stripped

### ISSUE THREAD

**Issue by vdh** [milesj/babel-plugin-typescript-to-proptypes#28]
Due to #8 and the plugin not being able to read/parse external types:

```tsx
type FooProps = {
  value: ExternalType["foo"] | null;
};
const Foo: FC<FooProps> = props => (<div>{props.value}</div>);
```

gets generated as something like:
```jsx
const Foo = props => (<div>{props.value}</div>);
Foo.propTypes = {
  value: PropTypes.oneOf(null),
};
```
It would be less problematic if the whole prop was skipped rather than attempting to strip external references. Generating an invalid validation rule based on a subset of the union is almost always going to be invalid and unhelpful.

**Comment by milesj** [comment]
Thanks. I'll update missing refs to just be null, which should fix this.
