### ISSUE TITLE
T[] vs Array<T>

### ISSUE THREAD

**Issue by jdeniau** [milesj/babel-plugin-typescript-to-proptypes#30]
Hi !

First of all, thank you for that promissing package.

I spotted an issue when using arrays.

You can reproduce it with the following code :

```typescript
import React from 'react';
interface KeyMapProps {
  stringArray: string[];   
  stringArray2: Array<string>;
}
function Foo({ stringArray, stringArray2 }: KeyMapProps) {
} 
```

The output will be:

```js
function Foo({
  stringArray,
  stringArray2
}) {
Foo.propTypes = {  
  stringArray: _propTypes.default.arrayOf(_propTypes.default.string).isRequired,
  stringArray2: _propTypes.default.any.isRequired
};  
```

stringArray2 output should be ` _propTypes.default.arrayOf(_propTypes.default.string).isRequired` too

The issue is with all types in arrays (not only string).

According to [the typescript documentation](https://www.typescriptlang.org/docs/handbook/basic-types.html#array), both writings are OK.

I saw that you rely on [`isTSArrayType`](https://github.com/milesj/babel-plugin-typescript-to-proptypes/blob/66d95cb99e43209cf216fdfb78dd10e9ecde7e12/src/convertBabelToPropTypes.ts#L186) from `@babel/core` package but I don't know if it's a babel issue or an issue in your package.

Thanks

**Comment by milesj** [comment]
Thanks! Will be fixed in next release.
