### ISSUE TITLE
TypeError: Cannot read property 'name' of null

### ISSUE THREAD

**Issue by smeijer** [milesj/babel-plugin-typescript-to-proptypes#34]
I'm trying to use this plugin, to get the proptypes visible in Storybook. But unfortunately, I cannot seem to start storybook with this plugin installed:

```
ERROR in ./src/context/withContext.tsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: Cannot read property 'name' of null
    at FunctionDeclaration (/home/smeijer/dev/myproject/node_modules/babel-plugin-typescript-to-proptypes/lib/index.js:164:57)
```

I'm not sure what info you need to get a better understanding of the error, but this is the `webpack` config I use:

```js
    config.module.rules.push({
      test: /\.(ts|tsx)$/,
      loader: require.resolve('babel-loader'),
      options: {
        presets: [[ 'react-app', { flow:false, typescript:true }]],
        plugins: [['babel-plugin-typescript-to-proptypes', { comments: true }]],
      },
    });

    config.resolve.extensions.push('.ts', '.tsx');
```

I'm using `babel-loader: 8.0.6` in `storybook: 5.3.17`

**Comment by milesj** [comment]
@smeijer It sounds like you have a function without a name, can you confirm?

**Comment by smeijer** [comment]
Yes, that I can confirm. We have a bunch of components defined without name. The file I mentioned in the opening post, holds something like:

```
import React, { ReactElement, FC } from 'react';
import MyContext from './MyContext';

export default function(Component): FC {
  return function WrappedWithMyContext(props): ReactElement {
    return (
      <MyContext.Consumer>
        {context => <Component {...props} mapContext={context} />}
      </MyContext.Consumer>
    );
  };
}
```

**Comment by milesj** [comment]
Ok cool, should be an easy fix. Thanks for the quick response.

**Comment by smeijer** [comment]
No problem. Let me know if there is a potential fix that I can test.

**Comment by milesj** [comment]
@smeijer Can you try the latest patch version?

**Comment by smeijer** [comment]
Thanks, no more errors on this side :tada:

**Comment by milesj** [comment]
Sweet!
