### ISSUE TITLE
Usage with Yarn 2.0 Plug'n'Play

### ISSUE THREAD

**Issue by ChrisSargent** [milesj/babel-plugin-typescript-to-proptypes#37]
Hey there, I'm using this with yarn 2 which supports pnp. When running, I get the following error
```
Error: babel-plugin-typescript-to-proptypes tried to access @babel/types, but it isn't declared in its dependencies;
this makes the require call ambiguous and unsound.

Required package: @babel/types (via "@babel/types")
Required by: babel-plugin-typescript-to-proptypes@virtual
```

The problems is reference here: https://next.yarnpkg.com/advanced/migration#a-package-is-trying-to-access-another-package-

I believe `@babel/types` should be listed in this project's dependencies.

**Comment by milesj** [comment]
Thanks for the report. In v1.4.
