### ISSUE TITLE
Order of type declaration is significant

### ISSUE THREAD

**Issue by thielium** [milesj/babel-plugin-typescript-to-proptypes#4]
## Steps to reproduce

The following fixture receives no `PropTypes`.
```jsx
import React from 'react';
export default class OutOfOrder extends React.Component<Props> {
  render() {
    return null;
  }
}
export interface Props {
  b: string;
}
```

Moving the `Props` to the top of the file does yield `PropTypes`.

[Here's](https://github.com/thielium/babel-plugin-typescript-to-proptypes/commit/ac7b9a1112cf76d0de5564e5a35049cbc39351fe) the fixture + expected snapshot; thought that might be easier than posting in the comment.

**Comment by milesj** [comment]
This is intentional. There were issues on generating prop types in `Program:exit`, so they're generated when a class is found. I'll look into this again but it may just be a caveat to deal with.

**Comment by milesj** [comment]
This should work now.
