### ISSUE TITLE
 Error: "default" is imported from external module "react" but never used

### ISSUE THREAD

**Issue by Andrei-Dimitrov** [milesj/babel-plugin-typescript-to-proptypes#51]
It looks like this plugin adds default React import, even if there are no propTypes should be added

This is an issue with Rollup when declaring React as an external module

I've created a [repl example](https://replit.com/@AndrewDimitrov/rollup-repro#src/main.ts) to demonstrate the issue

Could you please do something with this?

**Comment by milesj** [comment]
Will be fixed in next version.
