### ISSUE TITLE
'FunctionComponent' components don't output propTypes

### ISSUE THREAD

**Issue by JasonKaz** [milesj/babel-plugin-typescript-to-proptypes#7]
It seems like only `React.SFC` components are outputting propTypes and not `React.FunctionComponent` components. The reason I'm using `FunctionComponent` is because the TS types say that `React.SFC` is deprecated and instructs you to use `FunctionComponent`: 
![image](https://user-images.githubusercontent.com/959848/50619761-0f958180-0eb0-11e9-94fc-31fc46896d6c.png)

Input:
```typescript
interface Props {
  test: string;
}

export const FunctionComponent: React.FunctionComponent<Props> = () => <div />;

export const SFCComponent: React.SFC<Props> = () => <div />;
```

Output:
```js
var FunctionComponent = function FunctionComponent() {
  return React.createElement("div", null);
};

exports.FunctionComponent = FunctionComponent;

var SFCComponent = function SFCComponent() {
  return React.createElement("div", null);
};

exports.SFCComponent = SFCComponent;
SFCComponent.propTypes = {
  test: _propTypes.default.string.isRequired
};
```

I expect using both `React.SFC` and `React.FunctionComponent` to output propTypes.

**Comment by milesj** [comment]
Looks like I need another check here: https://github.com/milesj/babel-plugin-typescript-to-proptypes/blob/master/src/index.ts#L269

**Comment by milesj** [comment]
Fixed here https://github.com/milesj/babel-plugin-typescript-to-proptypes/commit/cadc16835246358d75368d0e1177a117f5bdd67a

**Comment by JasonKaz** [comment]
Works perfectly! Thanks for the quick response!

**Comment by milesj** [comment]
Np, luckily it was an easy fix!
